# Generated by Django 3.2.4 on 2021-08-01 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('emailId', models.CharField(max_length=50)),
                ('phoneNo', models.IntegerField()),
                ('price', models.IntegerField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=40)),
                ('pincode', models.IntegerField()),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, null=True)),
                ('description', models.TextField(null=True)),
                ('originalPrice', models.IntegerField(null=True)),
                ('discountedPrice', models.IntegerField(null=True)),
                ('image', models.CharField(max_length=200, null=True)),
                ('slug', models.SlugField(max_length=100, null=True)),
            ],
        ),
    ]
